### ISSUE TITLE
Pypy cannot find gevent module

### ISSUE THREAD

**Issue by Rongchao** [gevent-on-pypy/pypycore#8]
After followed instructions on read.me. Pypy still can not find gevent mudule.
Tried both on osx and ubuntu

**Comment by lvella** [comment]
Oh, you must run those instructions inside a virtualenv configured for PyPy:

```
$ cd project_dir
$ virtualenv -p /path/to/executable/pypy venv
$ source venv/bin/activate
(venv)$ pip install ...
```

That is so because the path PyPy search for modules is different from that of CPython, and by default "pip" install things on CPython's path. There must be some other way, but I don't know how...

**Comment by parasyte** [comment]
@lvella I just tried this with virtualenv:

```
$ virtualenv $(which pypy) pypy
$ source pypy/bin/activate
$ pip install git+git://github.com/schmir/gevent@pypy-hacks
    Successfully installed greenlet gevent
$ pip install cffi
    Successfully installed cffi pycparser
$ pip install git+git://github.com/gevent-on-pypy/pypycore
Downloading/unpacking git+git://github.com/gevent-on-pypy/pypycore
  Cloning git://github.com/gevent-on-pypy/pypycore to /var/folders/rq/mkjkc_sd18g7d1zddph9wjkm0000gn/T/pip-4aNF0P-build
  Running setup.py egg_info for package from git+git://github.com/gevent-on-pypy/pypycore
    Traceback (most recent call last):
      File "app_main.py", line 51, in run_toplevel
      File "app_main.py", line 575, in run_it
      File "<string>", line 16, in <module>
      File "/var/folders/rq/mkjkc_sd18g7d1zddph9wjkm0000gn/T/pip-4aNF0P-build/setup.py", line 7, in <module>
        import pypycore
      File "pypycore.py", line 19, in <module>
        ffi = FFI()
      File "/Users/jay/Desktop/pypy/site-packages/cffi/api.py", line 55, in __init__
        import _cffi_backend as backend
    ImportError: No module named _cffi_backend
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "app_main.py", line 51, in run_toplevel

  File "app_main.py", line 575, in run_it

  File "<string>", line 16, in <module>

  File "/var/folders/rq/mkjkc_sd18g7d1zddph9wjkm0000gn/T/pip-4aNF0P-build/setup.py", line 7, in <module>

    import pypycore

  File "pypycore.py", line 19, in <module>

    ffi = FFI()

  File "~/Desktop/pypy/site-packages/cffi/api.py", line 55, in __init__

    import _cffi_backend as backend

ImportError: No module named _cffi_backend

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/rq/mkjkc_sd18g7d1zddph9wjkm0000gn/T/pip-4aNF0P-build
Storing complete log in ~/.pip/pip.log
```

```
$ pip freeze
cffi==0.6
gevent==1.0dev
greenlet==0.4.1
pycparser==2.09.1
wsgiref==0.1.2
```

**Comment by lvella** [comment]
Well, this _cffi_backend is part of cffi installation... maybe you should try uninstalling and then reinstalling cffi ?
EDIT: it seems cffi is only supported on latests PyPy, are your version at least PyPy 2.0?

**Comment by parasyte** [comment]
Ok, found my problem! System pypy is v1.9.0. Sorry for noise.

```
$ pypy --version
Python 2.7.2 (341e1e3821ff, Jun 07 2012, 15:42:54)
[PyPy 1.9.0 with GCC 4.2.1]
```

**Comment by Rongchao** [comment]
Thank you !
